version: '3.9'

services:

  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: RkVAz75SRzkpfpA8
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: RkVAz75SRzkpfpA8
      WORDPRESS_DB_NAME: wordpressdb
  #   Extra config
  #   WORDPRESS_CONFIG_EXTRA: |
  #     define('UPLOADS', 'media');

  wp-cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    volumes:
      - ./wordpress:/var/www/html

volumes:
  wordpress: {}
  db: {}
