version: '3.9'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "${PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: "${DB_HOST}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_TABLE_PREFIX: "${TABLE_PREFIX}"
      WORDPRESS_DEBUG: "${DEBUG}"
      #   Extra config
      # WORDPRESS_CONFIG_EXTRA: |
      #   define('UPLOADS', ${UPLOADS});

  wp-cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: "${DB_HOST}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_TABLE_PREFIX: "${TABLE_PREFIX}"

volumes:
  wordpress: {}
  db: {}
